name: Robot Framework CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup Python and Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0