name: Running Terratest and Deploy Report Github Pages

on: push

jobs:
  run_test:
    runs-on: ubuntu-latest
    name: Setup Python and Run Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '121.0.6167.85'
      - run: robot -d reports/ tests/*.robot