name: Running Terratest and Deploy Report Github Pages

on: push

jobs:
  run_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: 'tests'